from pathlib import Path
root = Path(__file__).parent
base = (root / 'manuscript_full_novel.md').read_text(encoding='utf-8')
placements = [
    ('## Chapter Nine', 'longform_batch_01.md'),
    ('## Chapter Two', 'longform_batch_09.md'),
    ('## Chapter Thirteen', 'longform_batch_02.md'),
    ('## Chapter Seventeen', 'longform_batch_03.md'),
    ('## Chapter Twenty-Four', 'longform_batch_04.md'),
    ('# Epilogue', 'longform_batch_05.md'),
    ('## Chapter Fourteen', 'longform_batch_06.md'),
    ('## Chapter Nineteen', 'longform_batch_07.md'),
    ('# Epilogue', 'longform_batch_08.md'),
    ('# Epilogue', 'longform_batch_11.md'),
    ('# Epilogue', 'longform_batch_12.md'),
    ('# Epilogue', 'longform_batch_13.md'),
    ('# Epilogue', 'longform_batch_14.md'),
    ('# Epilogue', 'longform_batch_15.md'),
    ('# Epilogue', 'longform_batch_16.md'),
    ('# Epilogue', 'longform_batch_17.md'),
    ('# Epilogue', 'longform_batch_18.md'),
    ('# Epilogue', 'longform_batch_19.md'),
    ('# Epilogue', 'longform_batch_20.md'),
    ('# Epilogue', 'longform_batch_21.md'),
    ('# Epilogue', 'longform_batch_22.md'),
    ('# Epilogue', 'longform_batch_23.md'),
    ('# Epilogue', 'longform_batch_24.md'),
    ('# Epilogue', 'longform_batch_25.md'),
    ('# Epilogue', 'longform_batch_26.md'),
    ('# Epilogue', 'longform_batch_27.md'),
    ('# Epilogue', 'longform_batch_28.md'),
    ('# Epilogue', 'longform_batch_29.md'),
    ('# Epilogue', 'longform_batch_30.md'),
    ('# Epilogue', 'longform_batch_31.md'),
    ('# Epilogue', 'longform_batch_32.md'),
    ('# Epilogue', 'longform_batch_33.md'),
    ('# Epilogue', 'longform_batch_34.md'),
    ('# Epilogue', 'longform_batch_35.md'),
    ('# Epilogue', 'longform_batch_36.md'),
    ('# Epilogue', 'longform_batch_37.md'),
    ('# Epilogue', 'longform_batch_38.md'),
    ('# Epilogue', 'longform_batch_39.md'),
    ('# Epilogue', 'longform_batch_40.md'),
    ('# Epilogue', 'longform_batch_41.md'),
    ('# Epilogue', 'longform_batch_42.md'),
    ('# Epilogue', 'longform_batch_43.md'),
    ('# Epilogue', 'longform_batch_44.md'),
    ('# Epilogue', 'longform_batch_45.md'),
    ('# Epilogue', 'longform_batch_46.md'),
    ('# Epilogue', 'longform_batch_47.md'),
    ('# Epilogue', 'longform_batch_48.md'),
    ('# Epilogue', 'longform_batch_49.md'),
    ('# Epilogue', 'longform_batch_50.md'),
    ('# Epilogue', 'longform_batch_51.md'),
    ('# Epilogue', 'longform_batch_52.md'),
    ('# Epilogue', 'longform_batch_53.md'),
    ('# Epilogue', 'longform_batch_54.md'),
    ('# Epilogue', 'longform_batch_55.md'),
    ('# Epilogue', 'longform_batch_56.md'),
    ('# Epilogue', 'longform_batch_57.md'),
    ('# Epilogue', 'longform_batch_58.md'),
    ('# Epilogue', 'longform_batch_59.md'),
    ('# Epilogue', 'longform_batch_60.md'),
    ('# Epilogue', 'longform_batch_61.md'),
    ('# Epilogue', 'longform_batch_62.md'),
    ('# Epilogue', 'longform_batch_63.md'),
    ('# Epilogue', 'longform_batch_64.md'),
    ('# Epilogue', 'longform_batch_65.md'),
    ('# Epilogue', 'longform_batch_66.md'),
    ('# Epilogue', 'longform_batch_67.md'),
    ('# Epilogue', 'longform_batch_68.md'),
    ('# Epilogue', 'longform_batch_69.md'),
    ('# Epilogue', 'longform_batch_70.md'),
    ('# Epilogue', 'longform_batch_71.md'),
    ('# Epilogue', 'longform_batch_72.md'),
    ('# Epilogue', 'longform_batch_73.md'),
    ('# Epilogue', 'longform_batch_74.md'),
    ('# Epilogue', 'longform_batch_75.md'),
    ('# Epilogue', 'longform_batch_76.md'),
    ('# Epilogue', 'longform_batch_77.md'),
    ('# Epilogue', 'longform_batch_78.md'),
    ('# Epilogue', 'longform_batch_79.md'),
    ('# Epilogue', 'longform_batch_80.md'),
    ('# Epilogue', 'longform_batch_81.md'),
    ('# Epilogue', 'longform_batch_82.md'),
    ('# Epilogue', 'longform_batch_83.md'),
    ('# Epilogue', 'longform_batch_84.md'),
    ('# Epilogue', 'longform_batch_85.md'),
    ('# Epilogue', 'longform_batch_86.md'),
    ('# Epilogue', 'longform_batch_87.md'),
    ('# Epilogue', 'longform_batch_88.md'),
    ('# Epilogue', 'longform_batch_89.md'),
    ('# Epilogue', 'longform_batch_90.md'),
    ('# Epilogue', 'longform_batch_91.md'),
    ('# Epilogue', 'longform_batch_92.md'),
    ('# Epilogue', 'longform_batch_93.md'),
    ('# Epilogue', 'longform_batch_94.md'),
    ('# Epilogue', 'longform_batch_95.md'),
    ('# Epilogue', 'longform_batch_96.md'),
    ('# Epilogue', 'longform_batch_97.md'),
    ('# Epilogue', 'longform_batch_98.md'),
    ('# Epilogue', 'longform_batch_99.md'),
    ('# Epilogue', 'longform_batch_100.md'),
    ('# Epilogue', 'longform_batch_101.md'),
    ('# Epilogue', 'longform_batch_102.md'),
    ('# Epilogue', 'longform_batch_103.md'),
    ('# Epilogue', 'longform_batch_104.md'),
    ('# Epilogue', 'longform_batch_105.md'),
    ('# Epilogue', 'longform_batch_106.md'),
    ('# Epilogue', 'longform_batch_107.md'),
    ('# Epilogue', 'longform_batch_108.md'),
    ('# Epilogue', 'longform_batch_109.md'),
    ('# Epilogue', 'longform_batch_110.md'),
    ('# Epilogue', 'longform_batch_111.md'),
    ('# Epilogue', 'longform_batch_112.md'),
    ('# Epilogue', 'longform_batch_113.md'),
    ('# Epilogue', 'longform_batch_114.md'),
    ('# Epilogue', 'longform_batch_115.md'),
    ('# Epilogue', 'longform_batch_116.md'),
    ('# Epilogue', 'longform_batch_117.md'),
    ('## Chapter Six', 'longform_batch_10.md'),
]
text = base
for marker, filename in placements:
    if marker not in text:
        raise SystemExit(f'Missing marker: {marker}')
    heading = f'# LONG-FORM SUBPLOT EXPANSION — {filename.replace("longform_batch_", "BATCH ").replace(".md", "")}'
    if heading in text:
        continue
    addition = '\n\n' + heading + '\n\n' + (root / filename).read_text(encoding='utf-8') + '\n\n'
    text = text.replace(marker, addition + marker, 1)
(root / 'manuscript_90000_working.md').write_text(text, encoding='utf-8')
print(f'Wrote manuscript_90000_working.md with {len(text.split()):,} words')
